### ISSUE TITLE
units issues when using asdc data

### ISSUE THREAD

**Issue by olaurino** [ChandraCXC/iris-dev#101]
Jun 01, 2016 4:53:48 PM cfa.vo.iris.visualizer.plotter.PlotPreferences setYlabel
SEVERE: null
cfa.vo.iris.sed.SedException: non existent unit
        at cfa.vo.iris.sed.quantities.SPVYUnit.getFromUnitString(SPVYUnit.java:73)
        at cfa.vo.iris.visualizer.plotter.PlotPreferences.setYlabel(PlotPreferences.java:130)
        at cfa.vo.iris.visualizer.preferences.SedModel.setInitialUnits(SedModel.java:206)
        at cfa.vo.iris.visualizer.preferences.SedModel.setUnits(SedModel.java:178)
        at cfa.vo.iris.visualizer.preferences.SedModel.addSegment(SedModel.java:143)
        at cfa.vo.iris.visualizer.preferences.SedModel.refresh(SedModel.java:97)
        at cfa.vo.iris.visualizer.preferences.SedModel.<init>(SedModel.java:67)
        at cfa.vo.iris.visualizer.preferences.VisualizerComponentPreferences.update(VisualizerComponentPreferences.java:181)
        at cfa.vo.iris.visualizer.preferences.VisualizerComponentPreferences$VisualizerSedListener.processNotification(VisualizerComponentPreferences.java:298)
        at cfa.vo.iris.visualizer.preferences.VisualizerComponentPreferences$VisualizerSedListener.process(VisualizerComponentPreferences.java:286)
        at cfa.vo.iris.visualizer.preferences.VisualizerComponentPreferences$VisualizerSedListener.process(VisualizerComponentPreferences.java:281)
        at cfa.vo.iris.events.GenericEvent$1.run(GenericEvent.java:56)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by olaurino** [comment]
The error seems to result in other issues with the plotter, e.g. points not showing up and other weird behaviors with masking points. It might also be related with #100?

**Comment by olaurino** [comment]
This seems a duplicate of #105. I can't reproduce this issue any more, though, as the exceptions I mentioned in #105 are different and properly caught, as far as I can tell.
